version: '3'
services:
  connector-rssnews:
    image: aps3c/informint-rssnews:5.3.7
    environment:
      - OPENCTI_URL=http://localhost
      - OPENCTI_TOKEN=ChangeMe
      - CONNECTOR_ID=ChangeMe
      - CONNECTOR_TYPE=EXTERNAL_IMPORT
      - "CONNECTOR_NAME=RSS News"
      - CONNECTOR_SCOPE=identity,note
      - CONNECTOR_CONFIDENCE_LEVEL=75 # From 0 (Unknown) to 100 (Fully trusted)
      - CONNECTOR_UPDATE_EXISTING_DATA=false
      - CONNECTOR_LOG_LEVEL=info
      - CONNECTOR_LABEL_COLOR=#F53DBE
      - FETCHING_INTERVAL=6 # In hours, must be strictly greater than 1
      - "LIST_DATA_RSS=[['https://media.cert.europa.eu/rss?type=category&id=CERT-LatestNews&language=en,fr&duplicates=false','CERT EUROPA EU','%a, %d %b %Y %H:%M:%S +0200'],['https://media.cert.europa.eu/rss?type=category&id=VulnerabilitiesAll&language=en,fr&duplicates=false','CERT EUROPA EU','%a, %d %b %Y %H:%M:%S +0200'],['https://media.cert.europa.eu/rss?type=category&id=ThreatsStrategic&language=en,fr&duplicates=false','CERT EUROPA EU','%a, %d %b %Y %H:%M:%S +0200'],['https://www.cert.ssi.gouv.fr/feed/','CERT SSI GOUV FR','%a, %d %b %Y %H:%M:%S +0000'],['https://threatpost.com/feed/','ThreatPost','%a, %d %b %Y %H:%M:%S +0000']]"
      - "LIST_TWITTER_USER=["
    restart: always
