version: '3'
services:
  connector-cxsecurity-full:
    image: aps3c/informint-cxsecurity-manual:5.3.7
    environment:
      - OPENCTI_URL=http://localhost
      - OPENCTI_TOKEN=ChangeMe
      - CONNECTOR_ID=ChangeMe
      - CONNECTOR_TYPE=EXTERNAL_IMPORT
      - "CONNECTOR_NAME=CXSecurity"
      - CONNECTOR_SCOPE=identity,malware
      - CONNECTOR_CONFIDENCE_LEVEL=75 # From 0 (Unknown) to 100 (Fully trusted)
      - CONNECTOR_UPDATE_EXISTING_DATA=true
      - CONNECTOR_LOG_LEVEL=info
      - CONNECTOR_LABEL_COLOR=#33B5FF
      - CXSECURITY_INTERVAL=60 # In days, must be strictly greater than 1
    restart: always
