version: '3'
services:
  connector-cwe:
    image: aps3c/informint-cwe:5.3.6
    environment:
      - OPENCTI_URL=http://localhost
      - OPENCTI_TOKEN=ChangeMe
      - CONNECTOR_ID=ChangeMe
      - CONNECTOR_TYPE=EXTERNAL_IMPORT
      - "CONNECTOR_NAME=Common Weakness Enumeration"
      - CONNECTOR_SCOPE=identity,attack-pattern
      - CONNECTOR_CONFIDENCE_LEVEL=75 # From 0 (Unknown) to 100 (Fully trusted)
      - CONNECTOR_UPDATE_EXISTING_DATA=false
      - CONNECTOR_LOG_LEVEL=info
      - CONNECTOR_LABEL_COLOR='#C2B42C'
      - CWE_MITRE_DATA_FEED=https://cwe.mitre.org/data/xml/cwec_latest.xml.zip
      - CWE_INTERVAL=24 # In hours, must be strictly greater than 1
    restart: always
