version: '3'
services:
  connector-cpe:
    image: aps3c/informint-cpe:5.3.7
    environment:
      - OPENCTI_URL=http://localhost
      - OPENCTI_TOKEN=ChangeMe
      - CONNECTOR_ID=ChangeMe
      - CONNECTOR_TYPE=EXTERNAL_IMPORT
      - "CONNECTOR_NAME=Common Platform Enumeration"
      - CONNECTOR_SCOPE=identity,infrastructure
      - CONNECTOR_CONFIDENCE_LEVEL=75 # From 0 (Unknown) to 100 (Fully trusted)
      - CONNECTOR_UPDATE_EXISTING_DATA=false
      - CONNECTOR_LOG_LEVEL=info
      - CPE_NVD_DATA_FEED=https://nvd.nist.gov/feeds/xml/cpe/dictionary/official-cpe-dictionary_v2.3.xml.zip
      - CPE_INTERVAL=5 # In days, must be strictly greater than 1
    restart: always
